# Generated by Django 5.1.3 on 2026-04-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.CharField(max_length=100)),
                ('asignatura', models.CharField(max_length=100)),
                ('nota_1', models.DecimalField(decimal_places=2, max_digits=4)),
                ('nota_2', models.DecimalField(decimal_places=2, max_digits=4)),
                ('nota_3', models.DecimalField(decimal_places=2, max_digits=4)),
                ('promedio', models.DecimalField(decimal_places=2, editable=False, max_digits=4)),
            ],
            options={
                'ordering': ['estudiante', 'asignatura'],
            },
        ),
    ]
